module.exports = {
	button: "button",
	input: "input",
	select: "select",
	datetime: "datetime",
	datepicker: "datepicker",
	radio: "radio",
	checkbox: "checkbox",
	switch: "switch",
	slider: "slider",
	dropdown: "dropdown",
	file: "file",
	textarea: "textarea",
	ip: "ip",
	pager: "pager",
	loading: "loading",
	tabs: "tabs",
	customchecker: "customchecker",
	modal: "modal",
	scroll: "scroll",
	timeline: "timeline",
	stree: "stree",
	dialog: "dialog",
	progress: "progress",
	timepicker: "timepicker",
	pop: "pop",
	viewport : "viewport",
	virtualized: "virtualized",
	multiselect : "multiselect",
	ctxcheckbox: "ctxcheckbox" ,
	cascader: "cascader",
	counter: "counter"
};
